platform :ios, '16.0'

target 'iosApp' do
  use_frameworks! :linkage => :static

  pod 'MSAL', '2.7.0'
  pod 'composeApp', :path => '../composeApp'
  pod 'FirebaseCore'
  pod 'FirebaseMessaging'
  pod 'FirebaseDatabase'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
