package pe.lecordonbleu.universidadestudiante.util

class CountryCodes {
    private val countryCodes = mapOf(
        "Seleccione el país" to "",
        "Aruba" to "AW",
        "Australia" to "AU",
        "Austria" to "AT",
        "Azerbaiyán" to "AZ",
        "Bahamas" to "BS",
        "Bahráin" to "BH",
        "Bangladesh" to "BD",
        "Barbados" to "BB",
        "Belice" to "BZ",
        "Benín" to "BJ",
        "Bermudas" to "BM",
        "Bielorrusia" to "BY",
        "Bolivia" to "BO",
        "Bonaire, San Eustaquio y Saba" to "BQ",
        "Bosnia Herzegovina" to "BA",
        "Botswana" to "BW",
        "Brasil" to "BR",
        "Brunei Darussalam" to "BN",
        "Bulgaria" to "BG",
        "Burkina Faso" to "BF",
        "Burundi" to "BI",
        "Bután" to "BT",
        "Bélgica" to "BE",
        "Cabo Verde" to "CV",
        "Camboya" to "KH",
        "Camerún" to "CM",
        "Canadá" to "CA",
        "Chad" to "TD",
        "Chile" to "CL",
        "China" to "CN",
        "Chipre" to "CY",
        "Colombia" to "CO",
        "Comoras" to "KM",
        "Congo" to "CG",
        "Costa Rica" to "CR",
        "Costa de Marfil" to "CI",
        "Croacia" to "HR",
        "Curaçao" to "CW",
        "Dinamarca" to "DK",
        "Djibouti" to "DJ",
        "Dominica" to "DM",
        "Ecuador" to "EC",
        "Egipto" to "EG",
        "El Salvador" to "SV",
        "Emiratos Árabes Unidos" to "AE",
        "Eritrea" to "ER",
        "Eslovaquia" to "SK",
        "Eslovenia" to "SI",
        "España" to "ES",
        "Estados Federados de Micronesia" to "FM",
        "Estados Unidos" to "US",
        "Estonia" to "EE",
        "Etiopía" to "ET",
        "Federación Rusa" to "RU",
        "Fiji" to "FJ",
        "Filipinas" to "PH",
        "Finlandia" to "FI",
        "Francia" to "FR",
        "Gabón" to "GA",
        "Gambia" to "GM",
        "Georgia" to "GE",
        "Ghana" to "GH",
        "Gibraltar" to "GI",
        "Granada" to "GD",
        "Grecia" to "GR",
        "Groenlandia" to "GL",
        "Guadalupe" to "GP",
        "Guam" to "GU",
        "Guatemala" to "GT",
        "Guayana Francesa" to "GF",
        "Guernsey" to "GG",
        "Guinea" to "GN",
        "Guinea Ecuatorial" to "GQ",
        "Guinea-Bissau" to "GW",
        "Guyana" to "GY",
        "Haití" to "HT",
        "Honduras" to "HN",
        "Hong Kong, SAR" to "HK",
        "Hungría" to "HU",
        "India" to "IN",
        "Indonesia" to "ID",
        "Iraq" to "IQ",
        "Irlanda" to "IE",
        "Isla Bouvet" to "BV",
        "Isla Navidad" to "CX",
        "Isla Norfolk" to "NF",
        "Isla de Man" to "IM",
        "Islandia" to "IS",
        "Islas Caimán" to "KY",
        "Islas Cocos" to "CC",
        "Islas Cook" to "CK",
        "Islas Feroe" to "FO",
        "Islas Georgias del Sur y Sandwich del Sur" to "GS",
        "Islas Heard y McDonald" to "HM",
        "Islas Malvinas" to "FK",
        "Islas Marianas del Norte" to "MP",
        "Islas Marshall" to "MH",
        "Islas Salomón" to "SB",
        "Islas Turcas y Caicos" to "TC",
        "Islas Vírgenes, EE.UU." to "VI",
        "Islas Vírgenes, GB" to "VG",
        "Islas Wallis y Futuna" to "WF",
        "Islas Åland" to "AX",
        "Israel" to "IL",
        "Italia" to "IT",
        "Jamaica" to "JM",
        "Japón" to "JP",
        "Jersey" to "JE",
        "Jordania" to "JO",
        "Kazajistán" to "KZ",
        "Kenia" to "KE",
        "Kiribati" to "KI",
        "Kuwait" to "KW",
        "Kyrgyzstan" to "KG",
        "Laos" to "LA",
        "Lesotho" to "LS",
        "Letonia" to "LV",
        "Liberia" to "LR",
        "Libia" to "LY",
        "Liechtenstein" to "LI",
        "Lituania" to "LT",
        "Luxemburgo" to "LU",
        "Líbano" to "LB",
        "Macao, SAR" to "MO",
        "Macedonia" to "MK",
        "Madagascar" to "MG",
        "Malasia" to "MY",
        "Malawi" to "MW",
        "Maldivas" to "MV",
        "Mali" to "ML",
        "Malta" to "MT",
        "Marruecos" to "MA",
        "Martinica" to "MQ",
        "Mauricio" to "MU",
        "Mauritania" to "MR",
        "Mayotte" to "YT",
        "Mongolia" to "MN",
        "Montenegro" to "ME",
        "Montserrat" to "MS",
        "Mozambique" to "MZ",
        "Myanmar" to "MM",
        "México" to "MX",
        "Mónaco" to "MC",
        "Namibia" to "NA",
        "Nauru" to "NR",
        "Nepal" to "NP",
        "Nicaragua" to "NI",
        "Nigeria" to "NG",
        "Niue" to "NU",
        "Noruega" to "NO",
        "Nueva Caledonia" to "NC",
        "Nueva Zelanda" to "NZ",
        "Níger" to "NE",
        "Omán" to "OM",
        "Pakistán" to "PK",
        "Palaos" to "PW",
        "Panamá" to "PA",
        "Papúa Nueva Guinea" to "PG",
        "Paraguay" to "PY",
        "Países Bajos" to "NL",
        "Perú" to "PE",
        "Pitcairn" to "PN",
        "Polinesia Francesa" to "PF",
        "Polonia" to "PL",
        "Portugal" to "PT",
        "Puerto Rico" to "PR",
        "Qatar" to "QA",
        "Reino Unido" to "GB",
        "República Centroafricana" to "CF",
        "República Democrática del Congo" to "CD",
        "República Dominicana" to "DO",
        "República checa" to "CZ",
        "República de Corea" to "KR",
        "República de Moldova" to "MD",
        "Reunión" to "RE",
        "Ruanda" to "RW",
        "Rumanía" to "RO",
        "Sahara Occidental" to "EH",
        "Samoa" to "WS",
        "Samoa Americana" to "AS",
        "San Bartolomé" to "BL",
        "San Cristóbal y Nieves" to "KN",
        "San Marino" to "SM",
        "San Martín (Francia)" to "MF",
        "San Martín (Holanda)" to "SX",
        "San Pedro y Miquelón" to "PM",
        "San Vicente y las Granadinas" to "VC",
        "Santa Helena, Ascensión y Tristán de Acuña" to "SH",
        "Santa Lucía" to "LC",
        "Santa Sede (Ciudad del Vaticano)" to "VA",
        "Santo Tomé y Príncipe" to "ST",
        "Senegal" to "SN",
        "Serbia" to "RS",
        "Seychelles" to "SC",
        "Sierra Leona" to "SL",
        "Singapur" to "SG",
        "Somalia" to "SO",
        "Sri Lanka" to "LK",
        "Suazilandia" to "SZ",
        "Sudáfrica" to "ZA",
        "Sudán del Sur" to "SS",
        "Suecia" to "SE",
        "Suiza" to "CH",
        "Surinam" to "SR",
        "Svalbard y Jan Mayen" to "SJ",
        "Tailandia" to "TH",
        "Taiwán" to "TW",
        "Tanzania" to "TZ",
        "Tayikistán" to "TJ",
        "Territorio Británico del Océano Índico" to "IO",
        "Territorios Australes Franceses" to "TF",
        "Territorios Palestinos" to "PS",
        "Timor Oriental" to "TL",
        "Togo" to "TG",
        "Tokelau" to "TK",
        "Tonga" to "TO",
        "Trinidad y Tobago" to "TT",
        "Turkmenistán" to "TM",
        "Turquía" to "TR",
        "Tuvalu" to "TV",
        "Túnez" to "TN",
        "Ucrania" to "UA",
        "Uganda" to "UG",
        "Uruguay" to "UY",
        "Uzbekistán" to "UZ",
        "Vanuatu" to "VU",
        "Venezuela" to "VE",
        "Viet Nam" to "VN",
        "Yemen" to "YE",
        "Zambia" to "ZM",
        "Zimbabue" to "ZW"
    )

    fun getCode(countryName: String): String? {
        return countryCodes[countryName]
    }

    fun getCountryNames(): List<String> {
        return countryCodes.keys.toList()
    }
}
